package com.epam.bigdata.util

import org.apache.spark.sql.types.{DateType, DoubleType, IntegerType, LongType, ShortType, StringType, StructField, StructType}

case object SchemaHolder {

  val HOTELS_FORECAST_SCHEMA: StructType = new StructType()
    .add("precision", ShortType)
    .add("weather", new StructType()
      .add("lng", DoubleType)
      .add("lat", DoubleType)
      .add("avg_tmpr_f", DoubleType)
      .add("avg_tmpr_c", DoubleType)
      .add("wthr_date", DateType)
      .add("year", IntegerType)
      .add("month", ShortType)
      .add("day", ShortType))
    .add("hotel", new StructType()
      .add("id", LongType, nullable = true)
      .add("name", StringType)
      .add("country", StringType)
      .add("city", StringType)
      .add("address", StringType)
      .add("latitude", DoubleType)
      .add("longitude", DoubleType)
      .add("geohash", StringType))

  val EXPEDIA_SCHEMA: StructType = new StructType()
    .add("id", LongType)
    .add("date_time", StringType)
    .add("site_name", IntegerType)
    .add("posa_continent", IntegerType)
    .add("user_location_country", IntegerType)
    .add("user_location_region", IntegerType)
    .add("user_location_city", IntegerType)
    .add("orig_destination_distance", DoubleType)
    .add("user_id", IntegerType)
    .add("is_mobile", IntegerType)
    .add("is_package", IntegerType)
    .add("channel", IntegerType)
    .add("srch_ci", StringType)
    .add("srch_co", StringType)
    .add("srch_adults_cnt", IntegerType)
    .add("srch_children_cnt", IntegerType)
    .add("srch_rm_cnt", IntegerType)
    .add("srch_destination_id", IntegerType)
    .add("srch_destination_type_id", IntegerType)
    .add("hotel_id", LongType)
}
